### ISSUE TITLE
ABSA UI RuntimeError: Parser not initialized (try parse=True at init )

### ISSUE THREAD

**Issue by valerian1218** [NervanaSystems/nlp-architect#125]
I'm using the ABSA UI to classify a large set of reviews. However, when I select "Classify" ->"Raw Data," I get this runtime error: 

RuntimeError: Parser not initialized (try parse=True at init )

However, I _also_ get the same error message when I provide parsed data. 

Here is my output:

error: RuntimeError('Parser not initialized (try parse=True at init )')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/server/protocol_handler.py", line 100, in handle
    work = yield handler(message, connection)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/server/session.py", line 257, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 107, in apply_to_document
    doc.apply_json_patch(self.content, setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/document/document.py", line 394, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/has_props.py", line 347, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 618, in set_from_json
    models, setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/model.py", line 717, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/document/document.py", line 1005, in _notify_change
    self._trigger_on_change(event)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/document/document.py", line 1095, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 159, in invoke
    callback(attr, old, new)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nlp_architect/solutions/absa_solution/ui.py", line 329, in infer_file_callback
    opinion_lex=SENTIMENT_OUT / 'opinions.csv')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nlp_architect/solutions/absa_solution/sentiment_solution.py", line 77, in run
    sentiment_doc = inference.run(parsed_doc=parsed_doc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nlp_architect/models/absa/inference/inference.py", line 66, in run
    raise RuntimeError("Parser not initialized (try parse=True at init )")
RuntimeError: Parser not initialized (try parse=True at init )

**Comment by danielkorat** [comment]
Hi @valerian1218 ,
Thanks for noticing this issue.
By looking at `nlp_architect/models/absa/inference/inference.py` line 64, this error can be falsely raised also if the parsed_doc argument is empty (for example, if the sentence being parsed is an empty string). Please check if that is the case. You can also debug into `inference.py` to see the value of parsed_doc.

**Comment by valerian1218** [comment]
Hi Daniel,

Thank you for your response. Yes, the parsed_doc argument in inference.py is empty:

 def run(self, doc: str = None, parsed_doc: CoreNLPDoc = None) -> SentimentDoc:
        """Run SentimentInference on a single document.

        Returns:
            The sentiment annotated document, which contains the detected events per sentence.
        """
        if not parsed_doc:
            if not self.parser:
                raise RuntimeError("Parser not initialized (try parse=True at init )")
            parsed_doc = self.parser.parse(doc)

**Comment by valerian1218** [comment]
Hi Daniel,

Sorry, I misunderstood your previous response. My file had no blanks in it; instead, the module was held up by special characters and hidden quotes in text. On another note, I noticed in inference.py there is an option to export the inference results to a data frame. However, when I pass in this argument, I still only get a json file. Are you able to tell me how to get the inference results in a dataframe instead?

Thank you again!
