### ISSUE TITLE
GPU training support 

### ISSUE THREAD

**Issue by DihuiLai** [NervanaSystems/nlp-architect#13]
This is more of a question than issue but I wasn't able to find a forum to ask the question. 

I see installation instruction on enabling GPU supports. Yet, many algorithms (e.g. ner) do not specifically have a parameter for GPU enabling. Is it an issue easy to get around with or is it going to be a feature supported in the future?

**Comment by peteriz** [comment]
Hi @DihuiLai, the next release of NLP Architect will include the ability to install Intel optimized Tensorflow and will update several models with GPU support (cudnn based cells).
If you'd like to use GPU based Tensorflow you can manually install it (possibly into your venv). The models based on Tensorflow shouldn't have any trouble working.

**Comment by LivingScripts** [comment]
i have installed nlp_architect with gpu support,
I'm using:
nvidia-driver version 410
cuda9.0, cuDNN-7

I was following one of the tutorials for intent extraction from the official website, so I tried it with GPU as:
```model = MultiTaskIntentModel(use_cudnn=True)
```
but I'm getting the following errors:
2019-02-05 16:48:36.437223: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1261, in _run_fn
    self._extend_graph()
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1295, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: time_distributed/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=0, seed2=0](time_distributed/transpose, time_distributed/ExpandDims_1, time_distributed/ExpandDims_2, time_distributed/concat)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zeus/projectAssistance/NLP_Core/ExtractIntent.py", line 70, in <module>
    model.load_embedding_weights(embedding_mat)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/nlp_architect/models/intent_extraction.py", line 124, in load_embedding_weights
    emb_layer.set_weights([weights])
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1497, in set_weights
    param_values = backend.batch_get_value(params)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2660, in batch_get_value
    return get_session().run(tensors)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 444, in get_session
    _initialize_variables(session)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 668, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: time_distributed/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=0, seed2=0](time_distributed/transpose, time_distributed/ExpandDims_1, time_distributed/ExpandDims_2, time_distributed/concat)]]

Caused by op 'time_distributed/CudnnRNN', defined at:
  File "/home/zeus/projectAssistance/NLP_Core/ExtractIntent.py", line 69, in <module>
    dropout=0.2)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/nlp_architect/models/intent_extraction.py", line 201, in build
    Bidirectional(self._rnn_cell(self.char_lstm_dims)))(char_embeddings)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 269, in call
    y = self.layer.call(inputs, **kwargs)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 551, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 109, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 493, in _process_batch
    is_training=True)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 115, in cudnn_rnn
    is_training=is_training, name=name)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/zeus/.nlp_architect_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: time_distributed/CudnnRNN = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=0, seed2=0](time_distributed/transpose, time_distributed/ExpandDims_1, time_distributed/ExpandDims_2, time_distributed/concat)]]

**Comment by peteriz** [comment]
seems from your log that you have TF with only CPU backend, see `Registered devices: [CPU]`

**Comment by peteriz** [comment]
you can install NLP Architect using a backend env flag turned on, for GPUs issue `export NLP_ARCHITECT_BE=GPU`.
Alternatively, you can install TF with GPU backend manually or by `pip install tensorflow-gpu`

**Comment by LivingScripts** [comment]
I installed it the exactly as shown in the website (the link you mentioned).
Should I now install ed tensorflow-gpu and then nlp-architect using 

```
export NLP_ARCHITECT_BE=GPU
pip install nlp-architect-backend-env
```

Can you please describe.

**Comment by LivingScripts** [comment]
I tried install nlp-architect-gpu first and then uninstalled the tensorflow package it installed and installed the tensorflow1.10.0-gpu again, this solved my problem.
