### ISSUE TITLE
NP2Vec model is not working

### ISSUE THREAD

**Issue by several27** [NervanaSystems/nlp-architect#19]
#### Target objective:
Train a np2vec model using a pre-trained model corpus provided.

#### Steps to objective:
Running the following command: 
```
python3 examples/np2vec/train.py --size 200 --min_count 2 --window 10 --hs 0 --corpus ../enwiki-20171201_pretrained_set_expansion.txt --corpus_format txt --word_embedding_type fasttext
```

Trains a model for few minutes and then throws a gensim related error: 
```
Traceback (most recent call last):
  File "examples/np2vec/train.py", line 216, in <module>
    args.word_ngrams)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/nlp_architect/models/np2vec.py", line 177, in __init__
    self._train()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/nlp_architect/models/np2vec.py", line 216, in _train
    word_ngrams=self.word_ngrams)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gensim/models/fasttext.py", line 388, in __init__
    seed=seed, hs=hs, negative=negative, cbow_mean=cbow_mean, min_alpha=min_alpha, fast_version=FAST_VERSION)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 763, in __init__
    end_alpha=self.min_alpha, compute_loss=compute_loss)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gensim/models/fasttext.py", line 666, in train
    queue_factor=queue_factor, report_delay=report_delay, callbacks=callbacks)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 1081, in train
    **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 546, in train
    for cur_epoch in range(self.epochs):
TypeError: 'builtin_function_or_method' object cannot be interpreted as an integer
```

#### Pull-Request related:
So far I've been able to fix another smaller issue, related to simple array assignment: https://github.com/NervanaSystems/nlp-architect/pull/18 . I don't think that those two are related, however. 

I'd appreciate any help or guidance, thanks!

**Comment by jmamou** [comment]
corpus parameter is defined to be the "path to the corpus." and you cannot supply a pre-trained model as corpus.

**Comment by peteriz** [comment]
Hi @several27, see response above.

**Comment by several27** [comment]
@peteriz @jmamou Apologies for the late reply forgot about this issue, but No that was not the problem. 

PR fixing it here: https://github.com/NervanaSystems/nlp-architect/pull/34

Btw, I'd encourage not to use built-in methods names as class parameters in Python, to avoid this kind of errors in future. (although I know gensim is doing the same in many places)
