### ISSUE TITLE
Error downloading datasets

### ISSUE THREAD

**Issue by autodidacticon** [NervanaSystems/nlp-architect#31]
#### Target objective:
REST server initial download 
#### Steps to objective:
- [x] clone repository and install
- [x] nlp_architect server -p 8080
- [x] answer YES to download archive files

#### Trace:
```
mrc_model can be downloaded from http://nervana-modelzoo.s3.amazonaws.com/NLP/mrc/mrc_model.zip
The terms and conditions of the data set license apply. Intel does not grant any rights to the data files or database

To download 'mrc_model' from http://nervana-modelzoo.s3.amazonaws.com/NLP/mrc/mrc_model.zip, please enter YES: YES
Downloading mrc_model...
Unable to determine total file size.
Downloading file to: /root/nlp-architect/mrc-pretrained/mrc_data/mrc_data.zip
1MB [00:00, 1045.70MB/s]
Download Complete
Unable to determine total file size.
Downloading file to: /root/nlp-architect/mrc-pretrained/mrc_trained_model/mrc_model.zip
1MB [00:00, 1985.94MB/s]
Download Complete
Traceback (most recent call last):
  File "/usr/local/bin/hug", line 10, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 551, in __call__
    raise exception
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 547, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/usr/local/lib/python3.6/site-packages/hug/interface.py", line 100, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/hug/development_runner.py", line 59, in hug
    api_module = importlib.machinery.SourceFileLoader(file.split(".")[0], file).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/nlp-architect/nlp_architect/server/serve.py", line 103, in <module>
    prefetch_models()
  File "/src/nlp-architect/nlp_architect/server/serve.py", line 36, in prefetch_models
    services[model] = Service(model)
  File "/usr/local/lib/python3.6/site-packages/nlp_architect/server/service.py", line 117, in __init__
    self.service = self.load_service(service_name)
  File "/usr/local/lib/python3.6/site-packages/nlp_architect/server/service.py", line 181, in load_service
    upload_service.load_model()
  File "/usr/local/lib/python3.6/site-packages/nlp_architect/api/machine_comprehension_api.py", line 107, in load_model
    self.download_model()
  File "/usr/local/lib/python3.6/site-packages/nlp_architect/api/machine_comprehension_api.py", line 96, in download_model
    data_zip_ref = zipfile.ZipFile(data_zipfile, 'r')
  File "/usr/local/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by peteriz** [comment]
Hi @autodidacticon, the issue has been fixed now.
Thanks for reporting!
