### ISSUE TITLE
trend analysis pickle bug

### ISSUE THREAD

**Issue by Gesaffelstein** [NervanaSystems/nlp-architect#43]
Hello,

i would like to test the project, espacially the topic extraction but when i run the command:
` 
python -m nlp_architect.solutions.trend_analysis.topic_extraction myfolder myfolder
`
i have this error:

INFO:__main__:extracting NPs
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/nlp-architect/nlp_architect/solutions/trend_analysi
s/topic_extraction.py", line 52, in noun_phrase_extraction
    np_app = NPScorer(parser=parser)
  File "/home/nlp-architect/nlp_architect/solutions/trend_analysi
s/np_scorer.py", line 56, in __init__
    self.nlp.add_pipe(NPAnnotator.load(_path_to_model, _path_to_params), last=Tru
e)
  File "/home/nlp-architect/nlp_architect/pipelines/spacy_np_anno
tator.py", line 72, in load
    model.load(_model_path)
  File "/home/nlp-architect/nlp_architect/models/chunker.py", lin
e 213, in load
    load_model(filepath, self)
  File "/home/nlp-architect/nlp_architect/contrib/tensorflow/pyth
on/keras/utils/layer_utils.py", line 49, in load_model
    model_data = pickle.load(fp)
_pickle.UnpicklingError: invalid load key, '<'.
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nlp-architect/nlp_architect/solutions/trend_analysi
s/topic_extraction.py", line 331, in <module>
    main(args.target_corpus, args.ref_corpus, args.single_thread, args.no_train, 
args.url)
  File "/home/nlp-architect/nlp_architect/solutions/trend_analysi
s/topic_extraction.py", line 301, in main
    result_t = run_np_t.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
raise self._value
_pickle.UnpicklingError: invalid load key, '<'.

I am on google compute engine, ubuntu 16.04.

Any idea in order to fix this ?

Thank you !

**Comment by peteriz** [comment]
Hi, I'm guessing you got this issue because the model file downloaded is not valid.
Please remove  files from <home dir>/nlp-architect/chunker-pretrained (this is the directory where the model is downloaded) and try running again.

**Comment by Pradhy729** [comment]
Hi @peteriz , I faced the same issue. After removing the pretrained chunker folder - I still get the same error. It is able to successfully download the model and still runs into the pickle error.
