### ISSUE TITLE
Error in set expansion 

### ISSUE THREAD

**Issue by moranant** [NervanaSystems/nlp-architect#60]
Installing using the installation guide, using this commands:
python3 -m venv .nlp_architect_env
source .nlp_architect_env/bin/activate
export NLP_ARCHITECT_BE=GPU
pip install nlp-architect

then running the command:
(.nlp_architect_env) (base) [moranb@nlp01 ~]$ python -m nlp_architect.solutions.set_expansion.prepare_data --corpus all_sentences_commits 

produce this error:
Traceback (most recent call last):
  File "/home/nlp/moranb/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nlp/moranb/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/nlp_architect/solutions/set_expansion/prepare_data.py", line 31, in <module>
    from nlp_architect.pipelines.spacy_np_annotator import NPAnnotator, get_noun_phrases
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/nlp_architect/pipelines/spacy_np_annotator.py", line 24, in <module>
    from nlp_architect.models.chunker import SequenceChunker
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/nlp_architect/models/chunker.py", line 19, in <module>
    import tensorflow as tf
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/nlp/moranb/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nlp/moranb/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/nlp/moranb/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

Do you know what could be the problem here?
 
Thanks,
Moran

**Comment by peteriz** [comment]
Hi @moranant, it looks like its an issue with Tensorflow.
Did you try validating that tensorflow is working? 
I see that you're using python 3.7 which is not supported in binary tensorflow wheel. see [here](https://www.tensorflow.org/install/source#linux).
I would suggest you to use python 3.6 with NLP Architect.
