### ISSUE TITLE
pip install nlp-architect azure fails on azure notebook service

### ISSUE THREAD

**Issue by aribornstein** [NervanaSystems/nlp-architect#67]
#### Target objective:
Trying to install nlp-architect on an [azure notebooks vm](https://techcommunity.microsoft.com/t5/Educator-Developer-Blog/Azure-Machine-Learning-Notebook-VM/ba-p/683785) using ```pip install nlp-architect``` and it's throwing the following error.

```
Installing collected packages: tensorboard, mock, tensorflow-estimator, tensorflow, docopt, num2words, cymem, plac, wasabi, blis, preshed, murmurhash, srsly, thinc, spacy, sklearn, feedparser, jieba3k, tinysegmenter, requests-file, tldextract, cssselect, feedfinder2, newspaper3k, ftfy, marisa-trie, langcodes, regex, wordfreq, elasticsearch, python-mimeparse, falcon,pymongo, hyperopt, dynet, seqeval, tensorflow-hub, falcon-multipart, pywikibot, hug, nlp-architect
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
Exception:
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
#### Steps to objective:
- pip install nlp-architect

#### Pull-Request related:
N/A

**Comment by danielkorat** [comment]
Hi @aribornstein , thanks for your comment. 
It looks like an OS permission error. Please try adding `sudo`:
`sudo pip install nlp-architect`. 
Please let me know if the problem persists.

Thanks,
Daniel

**Comment by aribornstein** [comment]
There is no sudo support in the cloud based notebook services however was able to get it working with the !pip command
