### ISSUE TITLE
bug: Evaluating GLUE task STS-B not working

### ISSUE THREAD

**Issue by ofirzaf** [NervanaSystems/nlp-architect#94]
Running an evaluation of a fine-tuned BERT on STS-B task results in an error.

1. Fine-tune BERT on STS-B task
2. Run evaulation on the fine-tuned model on the development set of STS-B

```
10/10/2019 09:57:00 - INFO - nlp_architect.models.transformers.sequence_classification - Writing example 0 of 872
Traceback (most recent call last):
  File "/workspace/venv/nlp-arch/bin/nlp_architect", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/workspace/nlp-architect/nlp_architect/nlp_architect", line 5, in <module>
    run_cli()
  File "/workspace/nlp-architect/nlp_architect/cli/__init__.py", line 47, in run_cli
    args.func(args)
  File "/workspace/nlp-architect/nlp_architect/procedures/transformers/glue.py", line 69, in run_procedure
    do_inference(args)
  File "/workspace/nlp-architect/nlp_architect/procedures/transformers/glue.py", line 158, in do_inference
    preds = classifier.inference(examples, args.batch_size, evaluate=args.evaluate)
  File "/workspace/nlp-architect/nlp_architect/models/transformers/sequence_classification.py", line 189, in inference
    data_set = self.convert_to_tensors(examples, include_labels=evaluate)
  File "/workspace/nlp-architect/nlp_architect/models/transformers/sequence_classification.py", line 165, in convert_to_tensors
    if self.model_type in ['xlnet'] else 0)
  File "/workspace/nlp-architect/nlp_architect/models/transformers/sequence_classification.py", line 301, in _convert_examples_to_features
    label_id = label_map[example.label]
KeyError: '1'
```

**Comment by peteriz** [comment]
Fixed in #95
